# Generated by Django 3.2.7 on 2021-10-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscribe',
            fields=[
                ('id_suscribe', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
