# Generated by Django 3.2.9 on 2021-11-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id_configuraciones', models.AutoField(primary_key=True, serialize=False)),
                ('act_wifi', models.BooleanField()),
            ],
        ),
    ]
