# Generated by Django 3.2.9 on 2021-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('wifi', models.BooleanField()),
                ('on_off', models.BooleanField()),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
