# Generated by Django 3.2.9 on 2021-11-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='mail',
            new_name='email',
        ),
    ]
