# Generated by Django 3.2.7 on 2021-10-19 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invernadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('broker_conexion', models.CharField(max_length=100)),
                ('id_invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernadero.invernadero')),
            ],
        ),
    ]
